[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
base = "dark"
primaryColor = "#f7c600"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#1a1a19"
textColor = "#ffffff"

[client]
toolbarMode = "viewer"
